- name: Copy IPsec secrets block to ipsec.secrets
  ansible.builtin.copy:
    content: |
      {% for secret in secrets %}
      {{ secret.left }} {{ secret.right }} : PSK "{{ secret.psk }}"
      {% endfor %}
    dest: /etc/ipsec.secrets
    backup: yes
