---
- name: Install strongswam
  apt:
    name: 
      - strongswan 
      - strongswan-pki
      - libcharon-extra-plugins 
      - libcharon-extauth-plugins 
      - libstrongswan-extra-plugins 
      - libtss2-tcti-tabrmd0
